# List vs NDArray


In [1]:
import numpy as np

In [2]:
i = np.arange(1000)
l = range(1000)

In [5]:
%time for z in range(1,10): r=[x*2 for x in l]

Wall time: 1.01 ms


In [6]:
%time for z in range(1,10): r=i*2

Wall time: 0 ns


# Vectorized Functions

In [11]:
import numpy as np
arr = np.array(([1.,2,3,4],[1,2,3,4]))
arr2 = np.array(([1,2,3,4],[1,2,3,4]))


In [14]:

arr[arr>1]

array([2., 3., 4., 2., 3., 4.])

In [20]:
a = np.random.randn((10))
b = np.random.randn((10))

In [21]:
a > b

array([False,  True,  True, False, False,  True, False,  True, False,
        True])

In [22]:
a[a>b]

array([-1.06599059,  1.07635516,  0.54336953,  1.25039312, -0.18260962])

# Indexing | Slicing

# Fancy indexing

In [24]:
import numpy as np
a = np.array([1,2,3,4,5,65])
a[[2,3,4,5]]

array([ 3,  4,  5, 65])

In [25]:
a1 = np.random.randn(10,10)

In [26]:
a1

array([[ 0.11976191, -0.07312215, -1.38764359, -1.1274804 , -0.52248817,
        -1.305602  ,  0.23536294, -0.96108331, -0.05956827,  0.96288092],
       [ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
        -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377],
       [-0.61820394,  0.23242281, -1.02701639,  0.95078683, -1.40924205,
         2.05131629,  1.10885274, -0.45973936, -0.16296175,  0.43803774],
       [ 0.66398388, -0.10024017, -1.13489337, -0.87856486,  0.93475114,
         0.37013679, -0.34453497, -0.93231741, -0.83559949,  0.94759637],
       [-1.1307325 , -0.57509839, -0.64113032,  0.19516398, -0.33079471,
         0.36608269,  0.57055182,  0.07541791,  1.48230551,  0.93680973],
       [ 0.24023442, -0.72011687,  0.49841119, -1.85570516, -0.67504838,
         2.84446786,  0.32267728, -0.28676319,  0.24219157,  1.18039018],
       [-1.13604977, -1.37979225, -0.04870947, -1.09012041,  1.50779641,
        -1.80668762,  0.12594839, -2.21381215

In [31]:
a1[1]

array([ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
       -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377])

In [32]:
a1[0]

array([ 0.11976191, -0.07312215, -1.38764359, -1.1274804 , -0.52248817,
       -1.305602  ,  0.23536294, -0.96108331, -0.05956827,  0.96288092])

In [37]:
a1[0][7]

-0.9610833133887476

In [42]:
a1[1:10:5]

array([[ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
        -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377],
       [-1.13604977, -1.37979225, -0.04870947, -1.09012041,  1.50779641,
        -1.80668762,  0.12594839, -2.21381215,  2.31855432, -0.4151301 ]])

In [45]:
a1[::,0:1]

array([[ 0.11976191],
       [ 1.12603257],
       [-0.61820394],
       [ 0.66398388],
       [-1.1307325 ],
       [ 0.24023442],
       [-1.13604977],
       [-0.15170609],
       [ 1.59831638],
       [ 2.5595697 ]])

In [63]:
z1 = np.ones((5,5))

In [64]:
z1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
z1[1:-1,1:-1]=0

In [70]:
z1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Fast element-wise array functions

In [3]:
import numpy as np
x = np.array([1,2,3,5,6,7,9])
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 3.        ])

In [11]:
np.power(x,3)

array([  1,   8,  27, 125, 216, 343, 729], dtype=int32)