# List vs NDArray


In [1]:
import numpy as np

In [2]:
i = np.arange(1000)
l = range(1000)

In [5]:
%time for z in range(1,10): r=[x*2 for x in l]

Wall time: 1.01 ms


In [6]:
%time for z in range(1,10): r=i*2

Wall time: 0 ns


# Vectorized Functions

In [11]:
import numpy as np
arr = np.array(([1.,2,3,4],[1,2,3,4]))
arr2 = np.array(([1,2,3,4],[1,2,3,4]))


In [14]:

arr[arr>1]

array([2., 3., 4., 2., 3., 4.])

In [20]:
a = np.random.randn((10))
b = np.random.randn((10))

In [21]:
a > b

array([False,  True,  True, False, False,  True, False,  True, False,
        True])

In [22]:
a[a>b]

array([-1.06599059,  1.07635516,  0.54336953,  1.25039312, -0.18260962])

# Indexing | Slicing

# Fancy indexing

In [24]:
import numpy as np
a = np.array([1,2,3,4,5,65])
a[[2,3,4,5]]

array([ 3,  4,  5, 65])

In [25]:
a1 = np.random.randn(10,10)

In [26]:
a1

array([[ 0.11976191, -0.07312215, -1.38764359, -1.1274804 , -0.52248817,
        -1.305602  ,  0.23536294, -0.96108331, -0.05956827,  0.96288092],
       [ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
        -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377],
       [-0.61820394,  0.23242281, -1.02701639,  0.95078683, -1.40924205,
         2.05131629,  1.10885274, -0.45973936, -0.16296175,  0.43803774],
       [ 0.66398388, -0.10024017, -1.13489337, -0.87856486,  0.93475114,
         0.37013679, -0.34453497, -0.93231741, -0.83559949,  0.94759637],
       [-1.1307325 , -0.57509839, -0.64113032,  0.19516398, -0.33079471,
         0.36608269,  0.57055182,  0.07541791,  1.48230551,  0.93680973],
       [ 0.24023442, -0.72011687,  0.49841119, -1.85570516, -0.67504838,
         2.84446786,  0.32267728, -0.28676319,  0.24219157,  1.18039018],
       [-1.13604977, -1.37979225, -0.04870947, -1.09012041,  1.50779641,
        -1.80668762,  0.12594839, -2.21381215

In [31]:
a1[1]

array([ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
       -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377])

In [32]:
a1[0]

array([ 0.11976191, -0.07312215, -1.38764359, -1.1274804 , -0.52248817,
       -1.305602  ,  0.23536294, -0.96108331, -0.05956827,  0.96288092])

In [37]:
a1[0][7]

-0.9610833133887476

In [42]:
a1[1:10:5]

array([[ 1.12603257, -0.18864458,  0.21103415, -0.31674597,  1.70687619,
        -1.5077879 , -0.37559428, -1.04485236,  0.83239681,  0.15779377],
       [-1.13604977, -1.37979225, -0.04870947, -1.09012041,  1.50779641,
        -1.80668762,  0.12594839, -2.21381215,  2.31855432, -0.4151301 ]])

In [45]:
a1[::,0:1]

array([[ 0.11976191],
       [ 1.12603257],
       [-0.61820394],
       [ 0.66398388],
       [-1.1307325 ],
       [ 0.24023442],
       [-1.13604977],
       [-0.15170609],
       [ 1.59831638],
       [ 2.5595697 ]])

In [63]:
z1 = np.ones((5,5))

In [64]:
z1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [69]:
z1[1:-1,1:-1]=0

In [70]:
z1

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

# Fast element-wise array functions

In [3]:
import numpy as np
x = np.array([1,2,3,5,6,7,9])
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.23606798, 2.44948974,
       2.64575131, 3.        ])

In [11]:
np.power(x,3)

array([  1,   8,  27, 125, 216, 343, 729], dtype=int32)

In [13]:
y=np.array([6,6,6,6,6,6,6])

In [14]:
np.maximum(x,y)

array([6, 6, 6, 6, 6, 7, 9])

In [16]:
a = np.random.randn(100)
b= np.random.randn(100)
np.maximum(a,b)

array([ 9.09733790e-01,  1.57962636e+00,  4.33454378e-01, -3.59170145e-01,
        1.74226848e+00,  1.91695372e-01,  4.00589304e-01,  1.02467214e+00,
        6.20512309e-01,  1.62884311e+00,  1.05173446e+00,  9.31812278e-01,
        1.12275971e-01,  1.66239659e+00, -1.49146340e-01,  1.53438796e+00,
        7.33794181e-01,  9.76836594e-01,  4.51452332e-01,  1.35724537e+00,
       -2.75229505e-02, -9.33211558e-01,  1.86078928e+00,  1.75300110e+00,
        5.26343774e-02, -1.05367073e+00,  4.38348633e-01, -5.87197101e-02,
       -1.13013805e+00,  4.98786430e-01,  6.00722657e-01,  7.87475820e-01,
        3.57050429e-01,  2.62957540e-01,  1.01372962e+00,  8.56866923e-02,
        1.48250331e+00, -1.24630012e+00,  1.98252157e+00,  8.44673542e-01,
        6.35555089e-01,  6.27337202e-01,  8.05077762e-01, -1.33743735e-01,
        2.16690607e-01,  7.55285000e-01,  1.17682407e+00,  4.46221887e-01,
       -1.60965947e-01,  2.12314881e+00,  4.70277650e-01,  1.37322970e+00,
        8.91682507e-01,  

# Np.where

In [18]:
import numpy as np
salary = np.array([0,0,0,0,0,-1,-2,-4,25000,20000,30000])
np.where(salary<=0,"Not ok","OK")

array(['Not ok', 'Not ok', 'Not ok', 'Not ok', 'Not ok', 'Not ok',
       'Not ok', 'Not ok', 'OK', 'OK', 'OK'], dtype='<U6')

# Mathematical & Statistical Methods

In [32]:
import numpy as np

z = np.array([9,9,9,9,1,1,2,3,4,5,6,7,8,9])



In [20]:
np.mean(z)

5.0

In [21]:
np.cumsum(z)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [22]:
np.cumprod(z)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [23]:
z1 = z>7


In [24]:
np.sum(z1)

2

In [25]:
np.any(z1)

True

In [26]:
np.all(z1)

False

In [33]:
np.unique(z)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
z.sort()

In [35]:
z

array([1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 9, 9, 9, 9])

# File Input Output

In [ ]:
np.save()
np.load()
np.savez()